packages: 
# 所有在 packages/ 子目录下的 package
- 'packages/**'
# 不包括 packages/create-new-project/templates 下的
- '!packages/create-new-project/templates/**'
# 所有在 app/ 子目录下的 pacakge
- 'app/**'
# 不包括在 test 文件夹下的 package
- '!**/test/**'