name: "edge-ioc 构建检查流水线"

on:
  push:
    paths: 
      - "packages/edge-ioc/**"
    branches: 
      - master
      - release/*
      - fix/*
      - feature/*
  pull_request:
    paths: 
      - "packages/edge-ioc/**"
    branches:
      - master
      - release/*
      - fix/*
      - feature/*

jobs:
  inspections:
    name: 构建检查和持续集成
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: ESLint 检查
        run: "npx lerna run lint --scope @cc-infra/edge-ioc"
      - name: 构建检查
        run: "npx lerna run build --scope @cc-infra/edge-ioc"
      - name: 制品发布
        run: "npx lerna run dopublish --scope @cc-infra/ns-sdk"
        continue-on-error: true
      

